// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"

var resourceDataJson = &fyne.StaticResource{
	StaticName: "data.json",
	StaticContent: []byte(
		"{\"i\":[{\"Name\":\"pear\",\"Amount\":12.0,\"Emoji\":127816,\"Unit\":\"unit\"}],\"r\":[{\"Name\":\"test\",\"Ingredients\":[{\"Name\":\"cofee\",\"Amount\":200.0,\"Emoji\":99,\"Unit\":\"g\"}]}]}"),
}
